# Generated by Django 2.1.3 on 2018-12-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridResourceEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_id', models.CharField(max_length=200)),
                ('endpoint_url', models.CharField(max_length=200)),
                ('endpoint_interface_name', models.CharField(max_length=200)),
                ('running_jobs_count', models.IntegerField(default=0)),
                ('total_jobs_count', models.IntegerField()),
                ('waiting_jobs_count', models.IntegerField()),
                ('staging_jobs_count', models.IntegerField()),
                ('suspended_jobs_count', models.IntegerField()),
                ('quality_level', models.CharField(max_length=200)),
                ('health_state', models.CharField(max_length=200)),
                ('record_time', models.DateTimeField()),
            ],
        ),
    ]
