# Generated by Django 2.1.3 on 2018-12-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LdapScheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridresourceendpoint',
            name='staging_jobs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gridresourceendpoint',
            name='suspended_jobs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gridresourceendpoint',
            name='total_jobs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gridresourceendpoint',
            name='waiting_jobs_count',
            field=models.IntegerField(default=0),
        ),
    ]
